{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "%matplotlib inline\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "np.random.seed(0)\n",
    "plt.style.use(\"ggplot\")\n",
    "import tensorflow as tf\n",
    "from crf.langid_crf import *\n",
    "from helper.dataset_reader import read_tsv\n",
    "from deep_learning_models import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Tensorflow version: 2.9.0\n",
      "GPU detected: []\n"
     ]
    }
   ],
   "source": [
    "from tensorflow.python.client import device_lib\n",
    "\n",
    "print('Tensorflow version:', tf.__version__)\n",
    "print('GPU detected:', tf.config.list_physical_devices('GPU'))"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "outputs": [],
   "source": [
    "data = read_tsv('../dataset/comlid-data-140422-v1.tsv')"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "outputs": [],
   "source": [
    "all_data, words, tags = data"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "outputs": [
    {
     "data": {
      "text/plain": "133790"
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "len(words)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "outputs": [],
   "source": [
    "# create list of tuples from all words and all tags\n",
    "word_tag = list(zip(words, tags))\n",
    "# print(word_tag)\n",
    "# convert list to dataframe\n",
    "df_wordtag = pd.DataFrame(word_tag, columns=['Token','Label'])\n",
    "# df_wordtag"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "26890\n"
     ]
    }
   ],
   "source": [
    "unique_words = list(set(df_wordtag['Token'].values))\n",
    "unique_words.append(\"ENDPAD\")\n",
    "num_words = len(unique_words)\n",
    "print(num_words)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['ID', 'JV', 'MIX-ID-EN', 'EN', 'MIX-JV-EN', 'O', 'MIX-ID-JV']\n",
      "7\n"
     ]
    }
   ],
   "source": [
    "tags = list(set(df_wordtag[\"Label\"].values))\n",
    "print(tags)\n",
    "num_tags = len(tags)\n",
    "print(num_tags)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "outputs": [],
   "source": [
    "dt_pair = to_token_tag_list(data)\n",
    "# dt_pair[0]"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "outputs": [],
   "source": [
    "word2idx = {w: i + 1 for i, w in enumerate(words)}\n",
    "tag2idx = {t: i for i, t in enumerate(tags)}"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "outputs": [
    {
     "data": {
      "text/plain": "<Figure size 432x288 with 1 Axes>",
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXcAAAD4CAYAAAAXUaZHAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8QVMy6AAAACXBIWXMAAAsTAAALEwEAmpwYAAAVDUlEQVR4nO3dX0xb5+HG8QcDW9pSPP+BISjZRGGa0rIyzSgFrfK2eH9UtRM/LiK1YlIYmtRmVVSsTkObRC5YNdQVnGQiYpqqdepdL4a1bruy3LrSfDGntFqUblmpsi0oNAYfF0IK5d/5XVS1ssQOxmDAb76fq/jY55z3AfLw+vicQ5lt27YAAEZx7PUAAAA7j3IHAANR7gBgIModAAxEuQOAgSh3ADBQxV4P4FNXrlwpeF2v16u5ubkdHM3eI1PpMDGXiZkk83LV19fnfI6ZOwAYiHIHAANR7gBgIModAAxEuQOAgSh3ADAQ5Q4ABqLcAcBAlDsAGGjfXKG6H6z/6PtZl5f/9o+7PBIA2B5m7gBgIModAAxEuQOAgSh3ADAQ5Q4ABqLcAcBAlDsAGIhyBwAD5XUR049//GMdOHBADodD5eXlGh4e1uLiokKhkGZnZ1VTU6P+/n5VVVVJkiYmJhSNRuVwONTb26u2trZiZgAA3CTvK1RPnjyp6urqzONwOKzW1lZ1dXUpHA4rHA6rp6dH09PTisfjGh0dVTqd1tDQkE6fPi2HgzcJALBbCm7cRCIhv98vSfL7/UokEpnlnZ2dqqysVG1trerq6jQ1NbUzowUA5CXvmfvzzz8vSfr2t7+tQCCg+fl5uVwuSZLL5dLCwoIkybIstbS0ZNZzu92yLGsnxwwA2ERe5T40NCS32635+Xn94he/UH19fc7X2rad144jkYgikYgkaXh4WF6vN6/1sqmoqNjW+p+6mmP5Tmx7q3Yq035iYibJzFwmZpLMzZVNXuXudrslSU6nU+3t7ZqampLT6VQ6nZbL5VI6nc4cj/d4PEqlUpl1LcvKrH+jQCCgQCCQeTw3N1dwCK/Xu631N1PMbedS7Ex7wcRMkpm5TMwkmZfrdhPtTY+5Ly8va2lpKfPvv//97zp48KB8Pp9isZgkKRaLqb29XZLk8/kUj8e1urqqZDKpmZkZNTc370QOAECeNp25z8/P68UXX5Qkra+v6+tf/7ra2tp0//33KxQKKRqNyuv1KhgMSpIaGxvV0dGhYDAoh8Ohvr4+zpQBgF1WZud7kLzIrly5UvC6O/VWaz/9sQ7T3j5KZmaSzMxlYibJvFzbOiwDACg9lDsAGIhyBwADUe4AYCDKHQAMRLkDgIEodwAwEOUOAAbK+66Q2L79dJEUALMxcwcAA1HuAGAgyh0ADES5A4CBKHcAMBDlDgAGotwBwECUOwAYiHIHAANR7gBgIModAAxEuQOAgSh3ADAQ5Q4ABqLcAcBAlDsAGIhyBwADUe4AYCDKHQAMRLkDgIEodwAwUEW+L9zY2NDAwIDcbrcGBga0uLioUCik2dlZ1dTUqL+/X1VVVZKkiYkJRaNRORwO9fb2qq2trVjjBwBkkffM/S9/+YsaGhoyj8PhsFpbW3XmzBm1trYqHA5LkqanpxWPxzU6Oqqf//zneumll7SxsbHjAwcA5JZXuadSKU1OTurIkSOZZYlEQn6/X5Lk9/uVSCQyyzs7O1VZWana2lrV1dVpamqqCEMHAOSS12GZl19+WT09PVpaWsosm5+fl8vlkiS5XC4tLCxIkizLUktLS+Z1brdblmXdss1IJKJIJCJJGh4eltfrLTxERcW21v/U1RzLd2LbW93+TmXaT0zMJJmZy8RMkrm5stm03N966y05nU41NTXpwoULm27Qtu28dhwIBBQIBDKP5+bm8lovG6/Xu631N1PMbefafrEz7QUTM0lm5jIxk2Rervr6+pzPbVruFy9e1Llz5/T2229rZWVFS0tLOnPmjJxOp9LptFwul9LptKqrqyVJHo9HqVQqs75lWXK73TsQAwCQr02PuT/55JMaHx/X2NiYnn32WT344IM6ceKEfD6fYrGYJCkWi6m9vV2S5PP5FI/Htbq6qmQyqZmZGTU3Nxc3BQDgf+R9KuTNurq6FAqFFI1G5fV6FQwGJUmNjY3q6OhQMBiUw+FQX1+fHA5OpweA3bSlcn/ggQf0wAMPSJLuvfdeDQ4OZn1dd3e3uru7tz86AEBBmFIDgIEodwAwEOUOAAai3AHAQJQ7ABio4FMh7yTrP/p+1uXlv/3jLo8EAPLDzB0ADES5A4CBKHcAMBDlDgAGotwBwECUOwAYiHIHAANR7gBgIModAAzEFarbwJWrAPYrZu4AYCDKHQAMRLkDgIEodwAwEOUOAAai3AHAQJQ7ABiIcgcAA1HuAGAgrlAtglxXru7G9rk6FoDEzB0AjES5A4CBKHcAMBDlDgAG2vQD1ZWVFZ08eVJra2taX1/Xww8/rKNHj2pxcVGhUEizs7OqqalRf3+/qqqqJEkTExOKRqNyOBzq7e1VW1tbsXMAAG6wablXVlbq5MmTOnDggNbW1jQ4OKi2tjb97W9/U2trq7q6uhQOhxUOh9XT06Pp6WnF43GNjo4qnU5raGhIp0+flsPBmwQA2C2bNm5ZWZkOHDggSVpfX9f6+rrKysqUSCTk9/slSX6/X4lEQpKUSCTU2dmpyspK1dbWqq6uTlNTU0WMAAC4WV7nuW9sbOinP/2pPvjgA333u99VS0uL5ufn5XK5JEkul0sLCwuSJMuy1NLSklnX7XbLsqxbthmJRBSJRCRJw8PD8nq9hYeoqNjW+p+6uu0tFCbb2G+X6Xbj3ImvQ7Hs1PdpvzExl4mZJHNzZZNXuTscDv3qV7/S9evX9eKLL+q///1vztfatp3XjgOBgAKBQObx3NxcXutl4/V6t7X+Xss29kIz7eevQ6l/n3IxMZeJmSTzctXX1+d8bksHwu+55x4dOnRI77zzjpxOp9LptCQpnU6rurpakuTxeJRKpTLrWJYlt9tdyLgBAAXatNwXFhZ0/fp1SZ+cOXP+/Hk1NDTI5/MpFotJkmKxmNrb2yVJPp9P8Xhcq6urSiaTmpmZUXNzcxEjAAButulhmXQ6rbGxMW1sbMi2bXV0dOhrX/uavvSlLykUCikajcrr9SoYDEqSGhsb1dHRoWAwKIfDob6+Ps6UAYBdtmm5f+ELX9ALL7xwy/J7771Xg4ODWdfp7u5Wd3f39kcHACgIU2oAMBDlDgAGotwBwECUOwAYiHIHAANR7gBgIModAAxEuQOAgSh3ADAQ5Q4ABqLcAcBAed3PHcW1/qPv37LsqqTy3/5x9wcDwAjM3AHAQMzc97FsM3oAyAczdwAw0B05c2dGDMB0zNwBwECUOwAYiHIHAANR7gBgIModAAx0R54tY7JcZwJxtStwZ2HmDgAGotwBwECUOwAYiHIHAANR7gBgIModAAxEuQOAgTjPHVlxvjxQ2jYt97m5OY2NjenDDz9UWVmZAoGAHn30US0uLioUCml2dlY1NTXq7+9XVVWVJGliYkLRaFQOh0O9vb1qa2srdg4AwA02Lffy8nL94Ac/UFNTk5aWljQwMKCvfOUreuONN9Ta2qquri6Fw2GFw2H19PRoenpa8Xhco6OjSqfTGhoa0unTp+VwcAQIAHbLpo3rcrnU1NQkSbrrrrvU0NAgy7KUSCTk9/slSX6/X4lEQpKUSCTU2dmpyspK1dbWqq6uTlNTU0WMAAC42ZaOuSeTSV26dEnNzc2an5+Xy+WS9MkvgIWFBUmSZVlqaWnJrON2u2VZ1i3bikQiikQikqTh4WF5vd7CQ1RUbGn9qwXvqXRt9eub62u0m9+nUmFiLhMzSebmyibvcl9eXtbIyIiOHTumu+++O+frbNvOa3uBQECBQCDzeG5uLt+h3MLr9W5r/TvBTn19+D7dysRcJmaSzMtVX1+f87m8DoSvra1pZGREjzzyiA4fPixJcjqdSqfTkqR0Oq3q6mpJksfjUSqVyqxrWZbcbnfBgwcAbN2m5W7btsbHx9XQ0KDHHnsss9zn8ykWi0mSYrGY2tvbM8vj8bhWV1eVTCY1MzOj5ubmIg0fAJDNpodlLl68qDfffFMHDx7UT37yE0nSE088oa6uLoVCIUWjUXm9XgWDQUlSY2OjOjo6FAwG5XA41NfXx5kyALDLNi33L3/5y3r11VezPjc4OJh1eXd3t7q7u7c3MgBAwZhSA4CBKHcAMBDlDgAGotwBwECUOwAYiHIHAANxP3eUNO47D2RHud8hKEHgzsJhGQAwEOUOAAai3AHAQJQ7ABiID1TvcLk+aC3G9m/86058kAsUFzN3ADAQ5Q4ABqLcAcBAlDsAGIhyBwADUe4AYCDKHQAMRLkDgIG4iAk7otgXQwHYGsodJYFfHsDWUO7YEkoWKA2UO4x0u19C3NcGdwLKHXuCvwwFFBdnywCAgSh3ADAQ5Q4ABqLcAcBAm36gevbsWU1OTsrpdGpkZESStLi4qFAopNnZWdXU1Ki/v19VVVWSpImJCUWjUTkcDvX29qqtra2oAQAAt9q03L/xjW/oe9/7nsbGxjLLwuGwWltb1dXVpXA4rHA4rJ6eHk1PTysej2t0dFTpdFpDQ0M6ffq0HA7eICA/nEcP7IxNW/fQoUOZWfmnEomE/H6/JMnv9yuRSGSWd3Z2qrKyUrW1taqrq9PU1FQRhg0AuJ2CznOfn5+Xy+WSJLlcLi0sLEiSLMtSS0tL5nVut1uWZWXdRiQSUSQSkSQNDw/L6/UWMhRJUkVFxZbWv7r5S2Cw7fysZbPVn79SYGImydxc2ezoRUy2bef92kAgoEAgkHk8NzdX8H69Xm/W9XmLj2y287OWTa6fv1JmYibJvFz19fU5nyuo3J1Op9LptFwul9LptKqrqyVJHo9HqVQq8zrLsuR2uwvZBVA0XB2LO0FBn3T6fD7FYjFJUiwWU3t7e2Z5PB7X6uqqksmkZmZm1NzcvHOjBQDkZdOZ+6lTp/Tuu+/q2rVreuqpp3T06FF1dXUpFAopGo3K6/UqGAxKkhobG9XR0aFgMCiHw6G+vj7OlAGAPVBmb+VAeRFduXKl4HU55o5i2uxwjWnHcSUzM0nm5brdMXem1QBgIG75C2yCD2BRipi5A4CBKHcAMBDlDgAGotwBwECUOwAYiHIHAANR7gBgIModAAxEuQOAgSh3ADAQ5Q4ABqLcAcBAlDsAGIhyBwADUe4AYCDu5w4U6NP7vF+9aTn3ecd+wMwdAAxEuQOAgSh3ADAQ5Q4ABuIDVWCH8Qe1sR8wcwcAA1HuAGAgyh0ADES5A4CBKHcAMBBnywC7hLNosJuYuQOAgYo2c3/nnXf0u9/9ThsbGzpy5Ii6urqKtStd/b/Oom0bKDZm9CiGoszcNzY29NJLL+lnP/uZQqGQ/vrXv2p6eroYuwIAZFGUmfvU1JTq6ur0+c9/XpLU2dmpRCKh++67rxi7A4yUa0afS66Z/u22w7uD3bPb79CKUu6WZcnj8WQeezwevffee//zmkgkokgkIkkaHh5WfX194Tv887nC1wVMV+D/j239n9zH9izXLvdUUQ7L2LZ9y7KysrL/eRwIBDQ8PKzh4eFt729gYGDb29hvyFQ6TMxlYibJ3FzZFKXcPR6PUqlU5nEqlZLL5SrGrgAAWRSl3O+//37NzMwomUxqbW1N8XhcPp+vGLsCAGRRlGPu5eXl+uEPf6jnn39eGxsb+uY3v6nGxsZi7ErSJ4d4TEOm0mFiLhMzSebmyqbMznaAHABQ0rhCFQAMRLkDgIFK+sZhu3mLg2KZm5vT2NiYPvzwQ5WVlSkQCOjRRx/V4uKiQqGQZmdnVVNTo/7+flVVVe31cLdkY2NDAwMDcrvdGhgYMCLT9evXNT4+rsuXL6usrExPP/206uvrSzrXn/70J0WjUZWVlamxsVHHjx/XyspKyWU6e/asJicn5XQ6NTIyIkm3/ZmbmJhQNBqVw+FQb2+v2tra9nD0RWCXqPX1dfuZZ56xP/jgA3t1ddV+7rnn7MuXL+/1sLbMsiz7/ffft23btj/66CP7xIkT9uXLl+1XXnnFnpiYsG3bticmJuxXXnllD0dZmNdee80+deqU/ctf/tK2bduITL/+9a/tSCRi27Ztr66u2ouLiyWdK5VK2cePH7c//vhj27Zte2RkxH799ddLMtOFCxfs999/3w4Gg5lluXJcvnzZfu655+yVlRX76tWr9jPPPGOvr6/vxbCLpmQPy9x4i4OKiorMLQ5KjcvlUlNTkyTprrvuUkNDgyzLUiKRkN/vlyT5/f6Sy5ZKpTQ5OakjR45klpV6po8++kj/+Mc/9K1vfUuSVFFRoXvuuafkc21sbGhlZUXr6+taWVmRy+UqyUyHDh265d1FrhyJREKdnZ2qrKxUbW2t6urqNDU1tetjLqaSPSyTzy0OSk0ymdSlS5fU3Nys+fn5zIVfLpdLCwsLezy6rXn55ZfV09OjpaWlzLJSz5RMJlVdXa2zZ8/qP//5j5qamnTs2LGSzuV2u/X444/r6aef1mc+8xk99NBDeuihh0o6041y5bAsSy0tLZnXud1uWZa1J2MslpKdudt53OKglCwvL2tkZETHjh3T3XffvdfD2Za33npLTqcz847EFOvr67p06ZK+853v6IUXXtBnP/tZhcPhvR7WtiwuLiqRSGhsbEy/+c1vtLy8rDfffHOvh1V02frDNCU7czfpFgdra2saGRnRI488osOHD0uSnE6n0um0XC6X0um0qqur93iU+bt48aLOnTunt99+WysrK1paWtKZM2dKOpP0yc+cx+PJzPgefvhhhcPhks51/vx51dbWZsZ8+PBh/etf/yrpTDfKlePm/rAsS263e6+GWRQlO3M35RYHtm1rfHxcDQ0NeuyxxzLLfT6fYrGYJCkWi6m9vX2vhrhlTz75pMbHxzU2NqZnn31WDz74oE6cOFHSmSTpc5/7nDwej65cuSLpk2K87777SjqX1+vVe++9p48//li2bev8+fNqaGgo6Uw3ypXD5/MpHo9rdXVVyWRSMzMzam5u3suh7riSvkJ1cnJSv//97zO3OOju7t7rIW3ZP//5Tw0ODurgwYOZw0pPPPGEWlpaFAqFNDc3J6/Xq2AwuO9PRcvmwoULeu211zQwMKBr166VfKZ///vfGh8f19rammpra3X8+HHZtl3SuV599VXF43GVl5fri1/8op566iktLy+XXKZTp07p3Xff1bVr1+R0OnX06FG1t7fnzPGHP/xBr7/+uhwOh44dO6avfvWre5xgZ5V0uQMAsivZwzIAgNwodwAwEOUOAAai3AHAQJQ7ABiIcgcAA1HuAGCg/wf2+1xH82emAQAAAABJRU5ErkJggg==\n"
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "plt.hist([len(s) for s in dt_pair], bins=50)\n",
    "plt.show()"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "outputs": [],
   "source": [
    "from tensorflow.keras.preprocessing.sequence import pad_sequences\n",
    "\n",
    "max_len = 50\n",
    "\n",
    "X = [[word2idx[w[0]] for w in s] for s in dt_pair]\n",
    "X = pad_sequences(maxlen=max_len, sequences=X, padding=\"post\", value=num_words-1)\n",
    "\n",
    "y = [[tag2idx[w[1]] for w in s] for s in dt_pair]\n",
    "y = pad_sequences(maxlen=max_len, sequences=y, padding=\"post\", value=tag2idx[\"O\"])"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "outputs": [],
   "source": [
    "from sklearn.model_selection import train_test_split\n",
    "x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "outputs": [],
   "source": [
    "from tensorflow.keras import Model, Input\n",
    "from tensorflow.keras.layers import LSTM, Embedding, Dense, Flatten\n",
    "from tensorflow.keras.layers import TimeDistributed, SpatialDropout1D, Bidirectional"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model: \"model\"\n",
      "_________________________________________________________________\n",
      " Layer (type)                Output Shape              Param #   \n",
      "=================================================================\n",
      " input_1 (InputLayer)        [(None, 50)]              0         \n",
      "                                                                 \n",
      " embedding (Embedding)       (None, 50, 50)            1344500   \n",
      "                                                                 \n",
      " spatial_dropout1d (SpatialD  (None, 50, 50)           0         \n",
      " ropout1D)                                                       \n",
      "                                                                 \n",
      " bidirectional (Bidirectiona  (None, 50, 200)          120800    \n",
      " l)                                                              \n",
      "                                                                 \n",
      " time_distributed (TimeDistr  (None, 50, 7)            1407      \n",
      " ibuted)                                                         \n",
      "                                                                 \n",
      "=================================================================\n",
      "Total params: 1,466,707\n",
      "Trainable params: 1,466,707\n",
      "Non-trainable params: 0\n",
      "_________________________________________________________________\n"
     ]
    }
   ],
   "source": [
    "input_word = Input(shape=(max_len,))\n",
    "model = Embedding(input_dim=num_words, output_dim=50, input_length=max_len)(input_word)\n",
    "model = SpatialDropout1D(0.1)(model)\n",
    "model = Bidirectional(LSTM(units=100, return_sequences=True, recurrent_dropout=0.1))(model)\n",
    "out = TimeDistributed(Dense(num_tags, activation=\"softmax\"))(model)\n",
    "model = Model(input_word, out)\n",
    "model.summary()"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "outputs": [],
   "source": [
    "model.compile(optimizer=\"adam\",\n",
    "              loss=\"sparse_categorical_crossentropy\",\n",
    "              metrics=[\"accuracy\"])"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "outputs": [],
   "source": [
    "from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping\n",
    "from livelossplot.tf_keras import PlotLossesCallback"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/50\n"
     ]
    },
    {
     "ename": "InvalidArgumentError",
     "evalue": "Graph execution error:\n\nDetected at node 'model/embedding/embedding_lookup' defined at (most recent call last):\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel_launcher.py\", line 16, in <module>\n      app.launch_new_instance()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/traitlets/config/application.py\", line 845, in launch_instance\n      app.start()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 612, in start\n      self.io_loop.start()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 199, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n      self._run_once()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n      handle._run()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/asyncio/events.py\", line 81, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/ioloop.py\", line 688, in <lambda>\n      lambda f: self._run_callback(functools.partial(callback, future))\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/ioloop.py\", line 741, in _run_callback\n      ret = callback()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 814, in inner\n      self.ctx_run(self.run)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 775, in run\n      yielded = self.gen.send(value)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 381, in dispatch_queue\n      yield self.process_one()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 250, in wrapper\n      runner = Runner(ctx_run, result, future, yielded)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 741, in __init__\n      self.ctx_run(self.run)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 775, in run\n      yielded = self.gen.send(value)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 365, in process_one\n      yield gen.maybe_future(dispatch(*args))\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 268, in dispatch_shell\n      yield gen.maybe_future(handler(stream, idents, msg))\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 543, in execute_request\n      self.do_execute(\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 306, in do_execute\n      res = shell.run_cell(code, store_history=store_history, silent=silent)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2894, in run_cell\n      result = self._run_cell(\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2940, in _run_cell\n      return runner(coro)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3165, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3357, in run_ast_nodes\n      if (await self.run_code(code, result,  async_=asy)):\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3437, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"<ipython-input-18-21847a89921d>\", line 1, in <module>\n      get_ipython().run_cell_magic('time', '', '\\nchkpt = ModelCheckpoint(\"../model/model_weights.h5\", monitor=\\'val_loss\\',verbose=1, save_best_only=True, save_weights_only=True, mode=\\'min\\')\\n\\nearly_stopping = EarlyStopping(monitor=\\'val_accuracy\\', min_delta=0, patience=2, verbose=0, mode=\\'max\\', baseline=None, restore_best_weights=False)\\n\\ncallbacks = [PlotLossesCallback(), chkpt, early_stopping]\\n\\nhistory = model.fit(\\n    x=x_train,\\n    y=y_train,\\n    validation_data=(x_test,y_test),\\n    batch_size=32,\\n    epochs=50,\\n    callbacks=callbacks,\\n    verbose=1\\n)\\n')\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2399, in run_cell_magic\n      result = fn(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/decorator.py\", line 231, in fun\n      return caller(func, *(extras + args), **kw)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/magic.py\", line 187, in <lambda>\n      call = lambda f, *a, **k: f(*a, **k)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/magics/execution.py\", line 1321, in time\n      exec(code, glob, local_ns)\n    File \"<timed exec>\", line 7, in <module>\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1409, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1051, in train_function\n      return step_function(self, iterator)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1040, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1030, in run_step\n      outputs = model.train_step(data)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 889, in train_step\n      y_pred = self(x, training=True)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 490, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 458, in call\n      return self._run_internal_graph(\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 596, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/layers/core/embedding.py\", line 199, in call\n      out = tf.nn.embedding_lookup(self.embeddings, inputs)\nNode: 'model/embedding/embedding_lookup'\nindices[24,0] = 52627 is not in [0, 26890)\n\t [[{{node model/embedding/embedding_lookup}}]] [Op:__inference_train_function_6190]",
     "output_type": "error",
     "traceback": [
      "\u001B[0;31m---------------------------------------------------------------------------\u001B[0m",
      "\u001B[0;31mInvalidArgumentError\u001B[0m                      Traceback (most recent call last)",
      "\u001B[0;32m<timed exec>\u001B[0m in \u001B[0;36m<module>\u001B[0;34m\u001B[0m\n",
      "\u001B[0;32m~/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\u001B[0m in \u001B[0;36merror_handler\u001B[0;34m(*args, **kwargs)\u001B[0m\n\u001B[1;32m     65\u001B[0m     \u001B[0;32mexcept\u001B[0m \u001B[0mException\u001B[0m \u001B[0;32mas\u001B[0m \u001B[0me\u001B[0m\u001B[0;34m:\u001B[0m  \u001B[0;31m# pylint: disable=broad-except\u001B[0m\u001B[0;34m\u001B[0m\u001B[0;34m\u001B[0m\u001B[0m\n\u001B[1;32m     66\u001B[0m       \u001B[0mfiltered_tb\u001B[0m \u001B[0;34m=\u001B[0m \u001B[0m_process_traceback_frames\u001B[0m\u001B[0;34m(\u001B[0m\u001B[0me\u001B[0m\u001B[0;34m.\u001B[0m\u001B[0m__traceback__\u001B[0m\u001B[0;34m)\u001B[0m\u001B[0;34m\u001B[0m\u001B[0;34m\u001B[0m\u001B[0m\n\u001B[0;32m---> 67\u001B[0;31m       \u001B[0;32mraise\u001B[0m \u001B[0me\u001B[0m\u001B[0;34m.\u001B[0m\u001B[0mwith_traceback\u001B[0m\u001B[0;34m(\u001B[0m\u001B[0mfiltered_tb\u001B[0m\u001B[0;34m)\u001B[0m \u001B[0;32mfrom\u001B[0m \u001B[0;32mNone\u001B[0m\u001B[0;34m\u001B[0m\u001B[0;34m\u001B[0m\u001B[0m\n\u001B[0m\u001B[1;32m     68\u001B[0m     \u001B[0;32mfinally\u001B[0m\u001B[0;34m:\u001B[0m\u001B[0;34m\u001B[0m\u001B[0;34m\u001B[0m\u001B[0m\n\u001B[1;32m     69\u001B[0m       \u001B[0;32mdel\u001B[0m \u001B[0mfiltered_tb\u001B[0m\u001B[0;34m\u001B[0m\u001B[0;34m\u001B[0m\u001B[0m\n",
      "\u001B[0;32m~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/execute.py\u001B[0m in \u001B[0;36mquick_execute\u001B[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001B[0m\n\u001B[1;32m     52\u001B[0m   \u001B[0;32mtry\u001B[0m\u001B[0;34m:\u001B[0m\u001B[0;34m\u001B[0m\u001B[0;34m\u001B[0m\u001B[0m\n\u001B[1;32m     53\u001B[0m     \u001B[0mctx\u001B[0m\u001B[0;34m.\u001B[0m\u001B[0mensure_initialized\u001B[0m\u001B[0;34m(\u001B[0m\u001B[0;34m)\u001B[0m\u001B[0;34m\u001B[0m\u001B[0;34m\u001B[0m\u001B[0m\n\u001B[0;32m---> 54\u001B[0;31m     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n\u001B[0m\u001B[1;32m     55\u001B[0m                                         inputs, attrs, num_outputs)\n\u001B[1;32m     56\u001B[0m   \u001B[0;32mexcept\u001B[0m \u001B[0mcore\u001B[0m\u001B[0;34m.\u001B[0m\u001B[0m_NotOkStatusException\u001B[0m \u001B[0;32mas\u001B[0m \u001B[0me\u001B[0m\u001B[0;34m:\u001B[0m\u001B[0;34m\u001B[0m\u001B[0;34m\u001B[0m\u001B[0m\n",
      "\u001B[0;31mInvalidArgumentError\u001B[0m: Graph execution error:\n\nDetected at node 'model/embedding/embedding_lookup' defined at (most recent call last):\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel_launcher.py\", line 16, in <module>\n      app.launch_new_instance()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/traitlets/config/application.py\", line 845, in launch_instance\n      app.start()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 612, in start\n      self.io_loop.start()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 199, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n      self._run_once()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n      handle._run()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/asyncio/events.py\", line 81, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/ioloop.py\", line 688, in <lambda>\n      lambda f: self._run_callback(functools.partial(callback, future))\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/ioloop.py\", line 741, in _run_callback\n      ret = callback()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 814, in inner\n      self.ctx_run(self.run)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 775, in run\n      yielded = self.gen.send(value)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 381, in dispatch_queue\n      yield self.process_one()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 250, in wrapper\n      runner = Runner(ctx_run, result, future, yielded)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 741, in __init__\n      self.ctx_run(self.run)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 775, in run\n      yielded = self.gen.send(value)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 365, in process_one\n      yield gen.maybe_future(dispatch(*args))\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 268, in dispatch_shell\n      yield gen.maybe_future(handler(stream, idents, msg))\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 543, in execute_request\n      self.do_execute(\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 306, in do_execute\n      res = shell.run_cell(code, store_history=store_history, silent=silent)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2894, in run_cell\n      result = self._run_cell(\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2940, in _run_cell\n      return runner(coro)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3165, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3357, in run_ast_nodes\n      if (await self.run_code(code, result,  async_=asy)):\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3437, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"<ipython-input-18-21847a89921d>\", line 1, in <module>\n      get_ipython().run_cell_magic('time', '', '\\nchkpt = ModelCheckpoint(\"../model/model_weights.h5\", monitor=\\'val_loss\\',verbose=1, save_best_only=True, save_weights_only=True, mode=\\'min\\')\\n\\nearly_stopping = EarlyStopping(monitor=\\'val_accuracy\\', min_delta=0, patience=2, verbose=0, mode=\\'max\\', baseline=None, restore_best_weights=False)\\n\\ncallbacks = [PlotLossesCallback(), chkpt, early_stopping]\\n\\nhistory = model.fit(\\n    x=x_train,\\n    y=y_train,\\n    validation_data=(x_test,y_test),\\n    batch_size=32,\\n    epochs=50,\\n    callbacks=callbacks,\\n    verbose=1\\n)\\n')\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2399, in run_cell_magic\n      result = fn(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/decorator.py\", line 231, in fun\n      return caller(func, *(extras + args), **kw)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/magic.py\", line 187, in <lambda>\n      call = lambda f, *a, **k: f(*a, **k)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/magics/execution.py\", line 1321, in time\n      exec(code, glob, local_ns)\n    File \"<timed exec>\", line 7, in <module>\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1409, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1051, in train_function\n      return step_function(self, iterator)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1040, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1030, in run_step\n      outputs = model.train_step(data)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 889, in train_step\n      y_pred = self(x, training=True)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 490, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 458, in call\n      return self._run_internal_graph(\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 596, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/layers/core/embedding.py\", line 199, in call\n      out = tf.nn.embedding_lookup(self.embeddings, inputs)\nNode: 'model/embedding/embedding_lookup'\nindices[24,0] = 52627 is not in [0, 26890)\n\t [[{{node model/embedding/embedding_lookup}}]] [Op:__inference_train_function_6190]"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "\n",
    "chkpt = ModelCheckpoint(\"../model/model_weights.h5\", monitor='val_loss',verbose=1, save_best_only=True, save_weights_only=True, mode='min')\n",
    "\n",
    "early_stopping = EarlyStopping(monitor='val_accuracy', min_delta=0, patience=2, verbose=0, mode='max', baseline=None, restore_best_weights=False)\n",
    "\n",
    "callbacks = [PlotLossesCallback(), chkpt, early_stopping]\n",
    "\n",
    "history = model.fit(\n",
    "    x=x_train,\n",
    "    y=y_train,\n",
    "    validation_data=(x_test,y_test),\n",
    "    batch_size=32,\n",
    "    epochs=50,\n",
    "    callbacks=callbacks,\n",
    "    verbose=1\n",
    ")"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "outputs": [
    {
     "ename": "InvalidArgumentError",
     "evalue": "Graph execution error:\n\nDetected at node 'model/embedding/embedding_lookup' defined at (most recent call last):\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel_launcher.py\", line 16, in <module>\n      app.launch_new_instance()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/traitlets/config/application.py\", line 845, in launch_instance\n      app.start()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 612, in start\n      self.io_loop.start()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 199, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n      self._run_once()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n      handle._run()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/asyncio/events.py\", line 81, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/ioloop.py\", line 688, in <lambda>\n      lambda f: self._run_callback(functools.partial(callback, future))\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/ioloop.py\", line 741, in _run_callback\n      ret = callback()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 814, in inner\n      self.ctx_run(self.run)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 775, in run\n      yielded = self.gen.send(value)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 381, in dispatch_queue\n      yield self.process_one()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 250, in wrapper\n      runner = Runner(ctx_run, result, future, yielded)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 741, in __init__\n      self.ctx_run(self.run)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 775, in run\n      yielded = self.gen.send(value)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 365, in process_one\n      yield gen.maybe_future(dispatch(*args))\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 268, in dispatch_shell\n      yield gen.maybe_future(handler(stream, idents, msg))\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 543, in execute_request\n      self.do_execute(\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 306, in do_execute\n      res = shell.run_cell(code, store_history=store_history, silent=silent)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2894, in run_cell\n      result = self._run_cell(\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2940, in _run_cell\n      return runner(coro)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3165, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3357, in run_ast_nodes\n      if (await self.run_code(code, result,  async_=asy)):\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3437, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"<ipython-input-19-113a54cbdef7>\", line 1, in <module>\n      model.evaluate(x_test, y_test)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1756, in evaluate\n      tmp_logs = self.test_function(iterator)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1557, in test_function\n      return step_function(self, iterator)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1546, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1535, in run_step\n      outputs = model.test_step(data)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1499, in test_step\n      y_pred = self(x, training=False)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 490, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 458, in call\n      return self._run_internal_graph(\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 596, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/layers/core/embedding.py\", line 199, in call\n      out = tf.nn.embedding_lookup(self.embeddings, inputs)\nNode: 'model/embedding/embedding_lookup'\nindices[8,0] = 44720 is not in [0, 26890)\n\t [[{{node model/embedding/embedding_lookup}}]] [Op:__inference_test_function_6842]",
     "output_type": "error",
     "traceback": [
      "\u001B[0;31m---------------------------------------------------------------------------\u001B[0m",
      "\u001B[0;31mInvalidArgumentError\u001B[0m                      Traceback (most recent call last)",
      "\u001B[0;32m<ipython-input-19-113a54cbdef7>\u001B[0m in \u001B[0;36m<module>\u001B[0;34m\u001B[0m\n\u001B[0;32m----> 1\u001B[0;31m \u001B[0mmodel\u001B[0m\u001B[0;34m.\u001B[0m\u001B[0mevaluate\u001B[0m\u001B[0;34m(\u001B[0m\u001B[0mx_test\u001B[0m\u001B[0;34m,\u001B[0m \u001B[0my_test\u001B[0m\u001B[0;34m)\u001B[0m\u001B[0;34m\u001B[0m\u001B[0;34m\u001B[0m\u001B[0m\n\u001B[0m",
      "\u001B[0;32m~/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\u001B[0m in \u001B[0;36merror_handler\u001B[0;34m(*args, **kwargs)\u001B[0m\n\u001B[1;32m     65\u001B[0m     \u001B[0;32mexcept\u001B[0m \u001B[0mException\u001B[0m \u001B[0;32mas\u001B[0m \u001B[0me\u001B[0m\u001B[0;34m:\u001B[0m  \u001B[0;31m# pylint: disable=broad-except\u001B[0m\u001B[0;34m\u001B[0m\u001B[0;34m\u001B[0m\u001B[0m\n\u001B[1;32m     66\u001B[0m       \u001B[0mfiltered_tb\u001B[0m \u001B[0;34m=\u001B[0m \u001B[0m_process_traceback_frames\u001B[0m\u001B[0;34m(\u001B[0m\u001B[0me\u001B[0m\u001B[0;34m.\u001B[0m\u001B[0m__traceback__\u001B[0m\u001B[0;34m)\u001B[0m\u001B[0;34m\u001B[0m\u001B[0;34m\u001B[0m\u001B[0m\n\u001B[0;32m---> 67\u001B[0;31m       \u001B[0;32mraise\u001B[0m \u001B[0me\u001B[0m\u001B[0;34m.\u001B[0m\u001B[0mwith_traceback\u001B[0m\u001B[0;34m(\u001B[0m\u001B[0mfiltered_tb\u001B[0m\u001B[0;34m)\u001B[0m \u001B[0;32mfrom\u001B[0m \u001B[0;32mNone\u001B[0m\u001B[0;34m\u001B[0m\u001B[0;34m\u001B[0m\u001B[0m\n\u001B[0m\u001B[1;32m     68\u001B[0m     \u001B[0;32mfinally\u001B[0m\u001B[0;34m:\u001B[0m\u001B[0;34m\u001B[0m\u001B[0;34m\u001B[0m\u001B[0m\n\u001B[1;32m     69\u001B[0m       \u001B[0;32mdel\u001B[0m \u001B[0mfiltered_tb\u001B[0m\u001B[0;34m\u001B[0m\u001B[0;34m\u001B[0m\u001B[0m\n",
      "\u001B[0;32m~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/execute.py\u001B[0m in \u001B[0;36mquick_execute\u001B[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001B[0m\n\u001B[1;32m     52\u001B[0m   \u001B[0;32mtry\u001B[0m\u001B[0;34m:\u001B[0m\u001B[0;34m\u001B[0m\u001B[0;34m\u001B[0m\u001B[0m\n\u001B[1;32m     53\u001B[0m     \u001B[0mctx\u001B[0m\u001B[0;34m.\u001B[0m\u001B[0mensure_initialized\u001B[0m\u001B[0;34m(\u001B[0m\u001B[0;34m)\u001B[0m\u001B[0;34m\u001B[0m\u001B[0;34m\u001B[0m\u001B[0m\n\u001B[0;32m---> 54\u001B[0;31m     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n\u001B[0m\u001B[1;32m     55\u001B[0m                                         inputs, attrs, num_outputs)\n\u001B[1;32m     56\u001B[0m   \u001B[0;32mexcept\u001B[0m \u001B[0mcore\u001B[0m\u001B[0;34m.\u001B[0m\u001B[0m_NotOkStatusException\u001B[0m \u001B[0;32mas\u001B[0m \u001B[0me\u001B[0m\u001B[0;34m:\u001B[0m\u001B[0;34m\u001B[0m\u001B[0;34m\u001B[0m\u001B[0m\n",
      "\u001B[0;31mInvalidArgumentError\u001B[0m: Graph execution error:\n\nDetected at node 'model/embedding/embedding_lookup' defined at (most recent call last):\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel_launcher.py\", line 16, in <module>\n      app.launch_new_instance()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/traitlets/config/application.py\", line 845, in launch_instance\n      app.start()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 612, in start\n      self.io_loop.start()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 199, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n      self._run_once()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n      handle._run()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/asyncio/events.py\", line 81, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/ioloop.py\", line 688, in <lambda>\n      lambda f: self._run_callback(functools.partial(callback, future))\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/ioloop.py\", line 741, in _run_callback\n      ret = callback()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 814, in inner\n      self.ctx_run(self.run)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 775, in run\n      yielded = self.gen.send(value)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 381, in dispatch_queue\n      yield self.process_one()\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 250, in wrapper\n      runner = Runner(ctx_run, result, future, yielded)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 741, in __init__\n      self.ctx_run(self.run)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 775, in run\n      yielded = self.gen.send(value)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 365, in process_one\n      yield gen.maybe_future(dispatch(*args))\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 268, in dispatch_shell\n      yield gen.maybe_future(handler(stream, idents, msg))\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 543, in execute_request\n      self.do_execute(\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 306, in do_execute\n      res = shell.run_cell(code, store_history=store_history, silent=silent)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2894, in run_cell\n      result = self._run_cell(\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2940, in _run_cell\n      return runner(coro)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3165, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3357, in run_ast_nodes\n      if (await self.run_code(code, result,  async_=asy)):\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3437, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"<ipython-input-19-113a54cbdef7>\", line 1, in <module>\n      model.evaluate(x_test, y_test)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1756, in evaluate\n      tmp_logs = self.test_function(iterator)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1557, in test_function\n      return step_function(self, iterator)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1546, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1535, in run_step\n      outputs = model.test_step(data)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1499, in test_step\n      y_pred = self(x, training=False)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 490, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 458, in call\n      return self._run_internal_graph(\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 596, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/ahmadfathanhidayatullah/opt/anaconda3/lib/python3.8/site-packages/keras/layers/core/embedding.py\", line 199, in call\n      out = tf.nn.embedding_lookup(self.embeddings, inputs)\nNode: 'model/embedding/embedding_lookup'\nindices[8,0] = 44720 is not in [0, 26890)\n\t [[{{node model/embedding/embedding_lookup}}]] [Op:__inference_test_function_6842]"
     ]
    }
   ],
   "source": [
    "model.evaluate(x_test, y_test)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "idx2tag = {i: w for w,i in tag2idx.items()}\n",
    "\n",
    "def pred2label(pred):\n",
    "    out = []\n",
    "    for pred_i in pred:\n",
    "        for p in pred_i:\n",
    "            p_i = np.argmax(p)\n",
    "            out.append(idx2tag[p_i].replace(\"ENDPAD\", \"O\"))\n",
    "\n",
    "    return out\n",
    "\n",
    "def test2label(y_test):\n",
    "    tags = []\n",
    "    for val in y_test:\n",
    "        for v in val:\n",
    "            tags.append(idx2tag[v])\n",
    "\n",
    "    return tags\n",
    "\n",
    "y_test_pred = test2label(y_test)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "y_pred = model.predict(x_test, verbose=1)\n",
    "y_pred = pred2label(y_pred)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "from sklearn.metrics import classification_report, confusion_matrix\n",
    "\n",
    "labels = ['ID', 'JV', 'EN', 'MIX-ID-EN', 'MIX-ID-JV', 'MIX-JV-EN', 'O']\n",
    "\n",
    "print(classification_report(y_test_pred, y_pred, labels=labels))"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "import seaborn as sns\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "cm = confusion_matrix(y_test_pred, y_pred)\n",
    "# sns.heatmap(cm, annot=True, fmt='d', ax=ax)\n",
    "fig, ax = plt.subplots(figsize=(10,8))\n",
    "\n",
    "# plt.figure(figsize=(12, 10))\n",
    "# sns.set(rc={'figure.figsize': (14, 12)})\n",
    "sns.heatmap(cm, annot=True, fmt='d', ax=ax, annot_kws={'size': 16})\n",
    "# annot=True to annotate cells, ftm='g' to disable scientific notation\n",
    "\n",
    "\n",
    "# labels, title and ticks\n",
    "ax.set_title('Confusion Matrix', fontsize=16)\n",
    "ax.set_xlabel('Predicted labels', fontsize=16)\n",
    "ax.set_ylabel('True labels', fontsize=16)\n",
    "ax.xaxis.set_ticklabels(labels, rotation=45, fontsize=16)\n",
    "ax.yaxis.set_ticklabels(labels, rotation=0, fontsize=16)\n",
    "\n",
    "plt.show()"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "i = np.random.randint(0, x_test.shape[0]) #659\n",
    "p = model.predict(np.array([x_test[i]]))\n",
    "p = np.argmax(p, axis=-1)\n",
    "y_true = y_test[i]\n",
    "print(\"{:30}{:10}\\t {}\\n\".format(\"Word\", \"True\", \"Pred\"))\n",
    "print(\"-\" *60)\n",
    "for w, true, pred in zip(x_test[i], y_true, p[0]):\n",
    "    print(\"{:30}{:10}\\t{}\".format(words[w-1], tags[true], tags[pred]))"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}